spring:
  config:
    activate:
      on-profile: localbuild
  datasource:
    url: ${MARIADB_ADDRESS}
    username: ${MARIADB_USER}
    password: ${MARIADB_PW}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configtree:/run/secrets/
  datasource:
    url: ${be_db_url}
    user: ${be_db_user}
    password: ${be_db_password}
# driver-class-name & ddl-auto -> handled in docker-compose file
server:
  port: 8081